config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'users', :to => 'users/registrations#index'
  end


  resources :articles do
    member do
      get :renglish
      get :user_articles
    end
  end
 # get "/:subject", to: "articles#subject"
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :translated_articles, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true, length: {maximum: 10000}
  default_scope -> { order(created_at: :desc)}
  after_create :create_translated_article


  def create_translated_article(language = user.language)
    client = Aws::Translate::Client.new
    resp = client.translate_text({
                                   text: self.content, # required
                                   source_language_code: "en", # required
                                   target_language_code: language[-2..-1], # required
                                 })
    TranslatedArticle.create(article: self, translated: resp.translated_text,
                             language: language)
  end
end

app/models/translated_article.rb
class TranslatedArticle < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles
  has_one_attached :avatar do |attachable|
    attachable.variant :mini, resize_to_limit: [50, 50];
    attachable.variant :middle, resize_to_limit: [100, 100]

  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, uniqueness: true
  validates :username, uniqueness: true
  validates :avatar,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
            size:         { less_than: 5.megabytes,
                            message:   "should be less than 5MB" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :language])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :language, :avatar])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit update destroy]
  before_action :set_article, only: %i[show edit update destroy renglish]
  before_action :correct_user, only: %i[edit update, destroy]



  def renglish
    translated_articles = @article.translated_articles
    @translated = translated_articles.first.translated
    if current_user
      unless translated_articles.first.language == current_user.language
        tmp = false
        translated_articles.each do |t_article|
          if t_article.language == current_user.language
            @translated = t_article.translated
            tmp = true
            break
          end
        end
        unless tmp
          @article.create_translated_article(current_user.language)
          @translated = @article.translated_articles.reload.last.translated
        end
      end
    else
      flash[:alert] = "if you want choose you language for translated sentences "\
                         "please sign in and choose it in settings"
    end
  end

  def user_articles
    if params[:subject]
      @articles = Article.where(user_id: params[:id]).where(subject: params[:subject]).paginate(page: params[:page])
    else  
      @articles = Article.where(user_id: params[:id]).paginate(page: params[:page])
    end
  end


  def new
    @article = Article.new
  end


  def create
    
    @article = Article.new article_params
    @article.user = current_user
    if @article.save
      flash[:success] = "Congratulation! Article was created."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end


  def show; end

  def index
    if params[:subject]
      
      @articles = Article.where(subject: params[:subject]).paginate(page: params[:page])
    else  
      @articles = Article.all.paginate(page: params[:page])
    end  
  end

  def edit; end

  def update
    @article.user = current_user
    if @article.update(article_params)
      redirect_to @article
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "article was destroed"
    redirect_to root_url, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :subject)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def correct_user
    if !(current_user.admin)
      unless current_user && current_user == @article.user
        flash[:alert] = "You dont have permission to do this! Please log in"\
          "or create your own article!"

        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def mobile?
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    agent =~ /Mobile/ ? true : false
  end

  def admin?
    return false unless current_user
    current_user.admin?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="article">
    <h5>subject: <%= article.subject %> </h5>
    <h3><%= article.title %></h3>
    <p> <%= article.content %></p>
    <div style="display:flex;">
      <%= link_to "learn this", renglish_article_path(article),
                  class: "btn btn-primary" %>
      <% if article.user == current_user || admin? %>
        <%= link_to "edit", edit_article_path(article), class: "btn btn-primary" %>
        <%= link_to "delete", article, class: "btn btn-primary", data:
                    {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <% end %>
    </div>
      <span class="small-gray">
        Posted - <%= time_ago_in_words(article.created_at, "data-local": "time-ago") %> ago
        <br>
        By user - <%= link_to article.user.username, user_articles_article_path(article.user) %>
        <% if article.user.avatar.present? %>
        <%= image_tag(article.user.avatar.variant(:mini), class: "rounded-circle") %>
        <% else %>
          <%= image_tag("default_avatar_small.png") %>
      <% end %>
      </span>
</div>

app/views/articles/_form.html.erb
  <%= render 'shared/errors', object: article %>
  <%= form_with(model: article) do |f| %>
    <%= f.select :subject, %w{common for_beginners nature self-development grammar},
                                {}, {class: "form-control", style: "width: 30%;"} %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", style: "width: 30%;" %>
    <%= f.label :content %>
    <%= f.text_area :content,  class: "form-control" %>
    <br>
    <%= f.submit type, class: "btn btn-primary" %>
  <% end %>

app/views/articles/_many_articles.html.erb
 <div class="row">
   
   <div class="column left" style="margin: 3em; margin-right: 0;">
      <%= form_with   method: "get"  do |f| %>
        <%= f.label "choose subject" %>
        <%= f.select :subject, %w{common for_beginners nature self-development grammar},
                                  {}, {class: "form-control", style: "width: 50%"} %>
        <br>
        <%= f.submit "show", class: "btn btn-primary" %>
    <% end %>
    <br><br>
  </div>

  <div class=<%= mobile? ? "main_mobile" : "main column right"%> style="margin-left: 0;">
    <% unless @articles.any? %>
      <h3>unfortunatly there no one article with this subject but you can create!</h3>
      <%= link_to "Create article", new_article_path %>
    <% end %>
    <div class="pagination">
      <%= will_paginate @articles, class: "digg_pagination"%>
    </div>
    <%= render @articles %>
    <div class="pagination">
      <%= will_paginate @articles, class: "digg_pagination"%>
    </div>
  </div>
  
</div>

app/views/articles/edit.html.erb
<h3 style="width:50%;margin:auto; margin-top:1em;">update article <%= @article.title %></h3>
<div class=<%= mobile? ? "main_mobile" : "main" %>>
  <%= render "form", article: @article, type: "update" %>
  <span class="small-gray">
     By user - <%= @article.user.username %>
  </span>
</div>

app/views/articles/index.html.erb
<%= render "many_articles" %>

app/views/articles/new.html.erb
<div class=<%= mobile? ? "main_mobile" : "main" %>>
  <%= render "form", article: @article, type: "create" %>
</div>

app/views/articles/renglish.html.erb
<div class="<%= mobile? ? "main_mobile" : "main_sentence" %>" >
  <p id="sentence"><%= @article.title %></p>
  <p id="last-sentence" class="small-gray">this is last sentence in this article go to
    <%= link_to "home", root_path, class:"last-sentence" %> to see more article
  </p>
  <div class="sentence" data-controller="renglish">
    <input data-renglish-target="name" type="text" style="display:none"
           value="<%=  @article.content %>" >
    <input  style="visibility: hidden"
           value="<%= @translated %>" id="translated_article" >
    <button data-action="click->renglish#previous" class="btn btn-primary">previous</button>
    <button data-action="click->renglish#next" class="btn btn-primary">next</button>
  </div>
</div>

app/views/articles/show.html.erb
<div class=<%= mobile? ? "main_mobile" : "main" %>>
  <%= render @article %>
</div>

app/views/articles/user_articles.html.erb
<% if @articles.any? %>
  <h3 class="title">All articles by user <%= @articles.first.user.username %></h3>    
  <%= render "many_articles" %>
<% else %>
  <h3 class="title"> this user dont have  articles with this subject, pls choose another subject </h3>
  <div  style="margin: 3em; margin: auto; width: 50%;">
      <%= form_with   method: "get"  do |f| %>
        <%= f.label "choose subject" %>
        <%= f.select :subject, %w{common for_beginners nature self-development grammar},
                                  {}, {class: "form-control", style: "width: 15%"} %>
        <br>
        <%= f.submit "show", class: "btn btn-primary" %>
    <% end %>
    <br><br>
  </div>
<% end %>
  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p class="vio" style="margin-left: 0.5em;"> developed by Roman Kukla</p>
  </small>
  <nav style="margin-right: 0.5em;">
    <ul >
      <li class="vio"> currently seeking job, my info:</li>
      <li> <%= link_to 'linkedin', "https://www.linkedin.com/in/roman-kukla-software-engineer/", class: "vio" %></li>
      <li> <%= link_to 'CV', "https://kukla1989.github.io", class: "vio" %></li>
      <li> <%= link_to 'telegram', "https://telegram.me/roman_kukla", class: "vio" %></li>
      <li> <%= link_to 'mail me', "mailto:romankyk@gmail.com", class: "vio" %></li>
      <li> <%= link_to 'call me', "tel:+380930344021", class: "vio" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark" style="height: 5em;">
  <div class="container-fluid">
    <%= link_to image_tag("logo.png", style: "height:66%; width:66%; margin-right: 5em;"),
                          root_path %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path, class: "nav-link" %>
        <%= link_to "All users", users_path, class: "nav-link" %>
        <% if user_signed_in? %>
          <%= link_to "My articles", user_articles_article_path(current_user),
                                                          class: "nav-link" %>
          <%= link_to "Create article", new_article_path, class: "nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
              class: "nav-link"%>
          <%= link_to "Settings", edit_user_registration_path, class: "nav-link" %>
        <% else %>
          <%= link_to "Log in/sign up", new_user_session_path , class: "nav-link"%>
        <% end %>

      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>run english</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type == "alert" ? "danger" : "success"} ") %>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div class="alert alert-danger">
  form have <%= pluralize object.errors.count, "error"  %>
    <ul class="error">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>